#!/bin/bash
# client_setup.sh — PCDS student environment setup
#
# Generated by the instructor VM. INSTRUCTOR_FQDN is pre-configured below.
# Before distributing to students, run:
#   sed -i "s/REPLACE_WITH_INSTRUCTOR_FQDN/$(hostname --fqdn)/" client_setup.sh
#
# Usage (students run this once at the start of lab):
#   source client_setup.sh

INSTRUCTOR_FQDN="REPLACE_WITH_INSTRUCTOR_FQDN"
PCDS_URL="http://${INSTRUCTOR_FQDN}:2225"
PROFILE_SCRIPT="/etc/profile.d/pcds.sh"

# Warn if not sourced — vars won't take effect in the current shell otherwise
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    echo "NOTE: Run this with 'source client_setup.sh' so environment variables"
    echo "      take effect in your current session, not just future ones."
    echo ""
fi

UUID_DOMAIN=$(hostname --fqdn)

echo "=== PCDS Lab Environment Setup ==="
read -rp "Enter your full name: " STUDENT_NAME

if [[ -z "${STUDENT_NAME// }" ]]; then
    echo "ERROR: Name cannot be empty." >&2
    return 1 2>/dev/null || exit 1
fi

echo "Contacting instructor server..."

PAYLOAD=$(curl -sf -X POST "${PCDS_URL}/get-config" \
    -H "Content-Type: application/json" \
    -d "{\"name\": \"${STUDENT_NAME}\", \"uuid_domain\": \"${UUID_DOMAIN}\"}")

if [[ $? -ne 0 ]] || [[ -z "${PAYLOAD}" ]]; then
    echo "ERROR: Could not reach PCDS server at ${PCDS_URL}." >&2
    echo "       Check that the instructor's server is running." >&2
    return 1 2>/dev/null || exit 1
fi

# Write to profile.d for persistence across all future sessions (requires sudo)
echo "${PAYLOAD}" | sudo tee "${PROFILE_SCRIPT}" > /dev/null
sudo chmod 644 "${PROFILE_SCRIPT}"

# Activate in the current shell (works when sourced)
eval "${PAYLOAD}"

echo ""
echo "Done. Environment configured for ${STUDENT_NAME}."
echo "Variables are live now and will persist in all future terminal sessions."
